### ISSUE TITLE
List Type - function error

### ISSUE THREAD

**Issue by kfk12688** [Sharavanth/ho-app#40]
```
rest-service: Unhandled rejection TypeError: ["DS", "HN", "FN"] does not have a method named "split"
at D:\workFolder\ho-app\packages\rest-service\node_modules\ramda\src\invoker.js:39:11
at D:\workFolder\ho-app\packages\rest-service\node_modules\ramda\src\internal\_curryN.js:37:27
at D:\workFolder\ho-app\packages\rest-service\node_modules\ramda\src\internal\_arity.js:6:49
at getFieldProps (D:/workFolder/ho-app/packages/rest-service/src/utils/fieldNormalizer.js:13:26)
at normalizeField (D:/workFolder/ho-app/packages/rest-service/src/utils/fieldNormalizer.js:29:22)
at Array.map (native)
at Server.updateTable (D:/workFolder/ho-app/packages/rest-service/src/controllers/tableController.js:100:28)
at next (D:\workFolder\ho-app\packages\rest-service\node_modules\restify\lib\server.js:912:30)
at f (D:\workFolder\ho-app\packages\rest-service\node_modules\once\once.js:25:25)
at complete (D:\workFolder\ho-app\packages\rest-service\node_modules\passport\lib\middleware\authenticate.js:263:13)
at D:\workFolder\ho-app\packages\rest-service\node_modules\passport\lib\middleware\authenticate.js:270:15
at pass (D:\workFolder\ho-app\packages\rest-service\node_modules\passport\lib\authenticator.js:431:14)
at Authenticator.transformAuthInfo (D:\workFolder\ho-app\packages\rest-service\node_modules\passport\lib\authenticator.js:453:5)
at D:\workFolder\ho-app\packages\rest-service\node_modules\passport\lib\middleware\authenticate.js:267:22
at IncomingMessage.req.login.req.logIn (D:\workFolder\ho-app\packages\rest-service\node_modules\passport\lib\http\request.js:55:13)
at Strategy.strategy.success (D:\workFolder\ho-app\packages\rest-service\node_modules\passport\lib\middleware\authenticate.js:248:13)
```

**Comment by kfk12688** [comment]
Possible fix could be to use a CreatableMultiSelect as in [Tag Creation](http://jedwatson.github.io/react-select/)

**Comment by kfk12688** [comment]
close 5b40d21 select option works now.
